In [7]:
import numpy as np

Exercise 1: Matrix Addition & Subtraction

In [13]:
B = np.array([[11, 12], [13, 14]])
C = np.array([[15, 16], [17, 18]])

#Addition
add_result = B + C
print("B + C:")
print(add_result)

#Subtraction
sub_result = B - C
print("B - C:")
print(sub_result)

B + C:
[[26 28]
 [30 32]]
B - C:
[[-4 -4]
 [-4 -4]]


Exercise 2: Matrix Multiplication

In [15]:
# Define matrices for multiplication
D = np.array([[1, 2], [3, 4]])
E = np.array([[5, 6], [7, 8]])

In [19]:
multiply_result = D * E
print("D * E:")
print(multiply_result)

D * E:
[[ 5 12]
 [21 32]]


Exercise 3: Matrix Transpose

In [24]:
print("D:")
print(D)
transpose_result = D.T
print("Transpose of D:")
print(transpose_result)

D:
[[1 2]
 [3 4]]
Transpose of D:
[[1 3]
 [2 4]]


In [38]:
# Define a 3x3 square matrix
F = np.array([[4, 2, 3], [3, 7, 1], [2, 1, 5]])

# Calculating the determinant of the matrix
determinant = np.linalg.det(F)
print("Determinant of F:", determinant)

Determinant of F: 77.00000000000001


Exercise 5: Finding the Inverse

In [51]:
# Define an invertible 2x2 matrix
G = np.array([[1, 2], [3, 4]])

# Inverse of G
inverse_result = np.linalg.inv(G)
print("Inverse of G:")
print(inverse_result)

Inverse of G:
[[-2.   1. ]
 [ 1.5 -0.5]]


Additional Challenge 

In [58]:
# Generate a random 10x10 matrix
random_matrix_A = np.random.rand(10, 10)
print("Random 10x10 Matrix A:")
print(random_matrix_A)

Random 10x10 Matrix A:
[[0.68850274 0.45908287 0.99244508 0.58435342 0.21723081 0.57259652
  0.62463175 0.98396995 0.36855908 0.44051698]
 [0.36545763 0.81948714 0.48676899 0.87369619 0.28017775 0.05585679
  0.90622621 0.54488708 0.68257638 0.73075812]
 [0.60390477 0.85976527 0.52957804 0.18270262 0.33905606 0.2785761
  0.09468196 0.85493162 0.92702653 0.35126535]
 [0.73005862 0.67076478 0.97541007 0.18564959 0.01948371 0.38526493
  0.35208009 0.30969931 0.61799652 0.94823849]
 [0.43293438 0.68478893 0.57477889 0.9708796  0.22293053 0.06770477
  0.91673049 0.58831233 0.60555061 0.39476227]
 [0.89686553 0.20499641 0.08536066 0.60848301 0.1031871  0.90575587
  0.63430933 0.94007499 0.87523516 0.33068515]
 [0.24332374 0.58499018 0.47313695 0.04960729 0.18308216 0.3995641
  0.6456505  0.49151654 0.05497623 0.44207656]
 [0.55128531 0.26025281 0.04545502 0.41000776 0.55163808 0.75878768
  0.00211485 0.2639209  0.30644851 0.44060355]
 [0.01713291 0.1374343  0.69983942 0.16906947 0.87746748 0.

In [60]:
# Generate a second random 10x10 matrix
random_matrix_B = np.random.rand(10, 10)
print("\nRandom 10x10 Matrix B:")
print(random_matrix_B)


Random 10x10 Matrix B:
[[0.88680111 0.12076798 0.99230668 0.38371979 0.42376279 0.01806223
  0.88830915 0.85347509 0.13486831 0.07329603]
 [0.41892411 0.65166291 0.87912259 0.44448752 0.59383342 0.08005842
  0.07476217 0.93190133 0.37278843 0.80914058]
 [0.18458201 0.29989692 0.83607763 0.2580233  0.2417965  0.68345571
  0.58743627 0.43871163 0.88972325 0.32369356]
 [0.21799161 0.95980398 0.68066367 0.68165551 0.15264162 0.81337051
  0.85743983 0.50184193 0.89549273 0.16162074]
 [0.46307835 0.95562906 0.90320438 0.76219699 0.68198179 0.10892288
  0.42876935 0.44424375 0.70167042 0.7631551 ]
 [0.16195387 0.5699198  0.32099224 0.51888399 0.89591993 0.88116941
  0.94755339 0.82387981 0.63879112 0.6306165 ]
 [0.54187241 0.8130845  0.13878137 0.54164831 0.42717383 0.26663052
  0.24853062 0.71261169 0.34652301 0.95447515]
 [0.54434058 0.90281105 0.0592145  0.75635338 0.41052777 0.67959811
  0.02184017 0.55058009 0.08233365 0.31836243]
 [0.45903882 0.10159445 0.25643089 0.74448326 0.66236472

2.2 Matrix Addition

In [63]:
# Matrix Addition
addition_result = random_matrix_A + random_matrix_B
print("\nA + B (Matrix Addition):")
print(addition_result)


A + B (Matrix Addition):
[[1.57530385 0.57985085 1.98475176 0.96807321 0.64099361 0.59065875
  1.5129409  1.83744504 0.50342739 0.51381301]
 [0.78438174 1.47115005 1.36589159 1.31818371 0.87401117 0.13591521
  0.98098838 1.47678841 1.05536481 1.5398987 ]
 [0.78848678 1.15966219 1.36565567 0.44072592 0.58085256 0.96203181
  0.68211823 1.29364325 1.81674979 0.67495892]
 [0.94805024 1.63056876 1.65607374 0.8673051  0.17212533 1.19863544
  1.20951992 0.81154124 1.51348924 1.10985923]
 [0.89601272 1.64041799 1.47798327 1.73307659 0.90491233 0.17662764
  1.34549984 1.03255608 1.30722104 1.15791737]
 [1.0588194  0.77491622 0.4063529  1.127367   0.99910703 1.78692528
  1.58186272 1.7639548  1.51402628 0.96130165]
 [0.78519615 1.39807468 0.61191832 0.5912556  0.61025599 0.66619461
  0.89418112 1.20412823 0.40149924 1.39655172]
 [1.0956259  1.16306386 0.10466952 1.16636113 0.96216585 1.43838578
  0.02395502 0.81450099 0.38878216 0.75896598]
 [0.47617173 0.23902875 0.9562703  0.91355273 1.539832

2.3 Matrix Subtraction

In [66]:
# Matrix Subtraction
subtraction_result = random_matrix_A - random_matrix_B
print("\nA - B (Matrix Subtraction):")
print(subtraction_result)


A - B (Matrix Subtraction):
[[-1.98298367e-01  3.38314895e-01  1.38396103e-04  2.00633630e-01
  -2.06531983e-01  5.54534294e-01 -2.63677401e-01  1.30494855e-01
   2.33690774e-01  3.67220951e-01]
 [-5.34664749e-02  1.67824232e-01 -3.92353602e-01  4.29208665e-01
  -3.13655671e-01 -2.42016240e-02  8.31464037e-01 -3.87014256e-01
   3.09787946e-01 -7.83824569e-02]
 [ 4.19322768e-01  5.59868352e-01 -3.06499591e-01 -7.53206854e-02
   9.72595581e-02 -4.04879614e-01 -4.92754311e-01  4.16219994e-01
   3.73032800e-02  2.75717896e-02]
 [ 5.12067010e-01 -2.89039205e-01  2.94746397e-01 -4.96005917e-01
  -1.33157908e-01 -4.28105581e-01 -5.05359747e-01 -1.92142616e-01
  -2.77496209e-01  7.86617755e-01]
 [-3.01439711e-02 -2.70840129e-01 -3.28425481e-01  2.08682615e-01
  -4.59051263e-01 -4.12181103e-02  4.87961145e-01  1.44068583e-01
  -9.61198120e-02 -3.68392827e-01]
 [ 7.34911660e-01 -3.64923389e-01 -2.35631575e-01  8.95990244e-02
  -7.92732830e-01  2.45864611e-02 -3.13244057e-01  1.16195175e-01
   2

2.4 Matrix Multiplication

In [69]:
# Matrix Multiplication
multiplication_result = np.dot(random_matrix_A, random_matrix_B)
print("\nA * B (Matrix Multiplication):")
print(multiplication_result)


A * B (Matrix Multiplication):
[[2.55572201 3.35214839 3.01796586 3.07104427 2.56064126 3.19443606
  3.20866336 3.88300858 3.11768333 2.36866407]
 [2.52865474 3.39887713 2.82846775 3.09292873 2.34765236 2.88914564
  2.98815752 3.87920115 3.2505318  2.44461122]
 [2.34164221 2.50779628 2.68650232 2.76879128 2.48127282 2.33436714
  2.51159986 3.61945564 2.42536294 1.91441147]
 [2.30610609 2.17226317 2.80418427 2.3334766  2.21321095 2.78453183
  3.2051887  3.60860594 3.04843576 1.81037902]
 [2.38200773 3.32124305 2.78889774 2.99339514 2.20579307 2.69042335
  2.80349824 3.66087998 2.98543148 2.3327125 ]
 [2.63568559 3.02762681 2.37099971 3.22355485 2.802131   3.00995174
  3.39988425 4.0616994  2.58648519 2.07884011]
 [1.55752904 2.121344   1.69599265 1.74778116 1.66068456 1.74726141
  1.64834505 2.4164833  1.81622468 1.86158709]
 [1.56520327 2.01784408 2.01344253 1.99030865 1.92105741 1.89747706
  2.47041145 2.48123745 2.06914761 1.40231601]
 [1.68182531 2.79960561 2.19555588 2.46836596 2.

2.5 Transpose of a Matrix

In [72]:
# Transpose of random_matrix_A
transpose_result_A = random_matrix_A.T
print("\nTranspose of Matrix A:")
print(transpose_result_A)

# Transpose of random_matrix_B
transpose_result_B = random_matrix_B.T
print("\nTranspose of Matrix B:")
print(transpose_result_B)


Transpose of Matrix A:
[[0.68850274 0.36545763 0.60390477 0.73005862 0.43293438 0.89686553
  0.24332374 0.55128531 0.01713291 0.38434964]
 [0.45908287 0.81948714 0.85976527 0.67076478 0.68478893 0.20499641
  0.58499018 0.26025281 0.1374343  0.31997537]
 [0.99244508 0.48676899 0.52957804 0.97541007 0.57477889 0.08536066
  0.47313695 0.04545502 0.69983942 0.62256365]
 [0.58435342 0.87369619 0.18270262 0.18564959 0.9708796  0.60848301
  0.04960729 0.41000776 0.16906947 0.29163199]
 [0.21723081 0.28017775 0.33905606 0.01948371 0.22293053 0.1031871
  0.18308216 0.55163808 0.87746748 0.48278885]
 [0.57259652 0.05585679 0.2785761  0.38526493 0.06770477 0.90575587
  0.3995641  0.75878768 0.93555699 0.18041367]
 [0.62463175 0.90622621 0.09468196 0.35208009 0.91673049 0.63430933
  0.6456505  0.00211485 0.19934692 0.75476545]
 [0.98396995 0.54488708 0.85493162 0.30969931 0.58831233 0.94007499
  0.49151654 0.2639209  0.59533211 0.40453886]
 [0.36855908 0.68257638 0.92702653 0.61799652 0.60555061 

Learning Assessment Questions

 Question 1: Explain what a matrix is and provide an example of a 3×23 \times 23×2 matrix. Using NumPy, write code to create this matrix.

A matrix is a table that has 2 dimensions called "Rows" or "Columns". This contains values such as numbers, expressions or symbols.

The following code creates a 3x2 and 2x3 matrix.

In [83]:
Matrix1 = np.array([[1,2], [3,4], [5,6]])
Matrix2 = np.array([[1,2,3], [4,5,6]])

print("Matrix 1 is 3x2")
print(Matrix1)
print("Matrix 2 is 2x3")
print(Matrix2)

Matrix 1 is 3x2
[[1 2]
 [3 4]
 [5 6]]
Matrix 2 is 2x3
[[1 2 3]
 [4 5 6]]


Question 2: Given two matrices A and B, describe the conditions necessary for performing matrix addition and matrix multiplication. 
Write code to add and multiply two 5×5 matrices using NumPy.


Suppose we have 2 arrays of 5x5 in size. Before we begin any mathematical procedures, we first have to view their matrix dimensions as a cartesian plane. "Rows" and "Columns" will act as "X" and "Y" respectively in relation to a cartesian plane concept. With this in mind, we can now begin.

When it comes to addition, the sizes of the matrices have to be the same. When this condition is satisfied, each element from each matrix can be added to each other, given they both have the same dimension locations. For example: Element from Matrix A with positions Row1 and Column1 can only be added to another element from the latter matrix with the same positions as Row1 and Column1.

In multiplication however, the conditions to be satisfied differ. The initial matrix's column size has to be the same as the opposiing matrix's row size. For example, matrices 3x2 and 2x4 satisfy the conditions to be multiplied. However, if they were switched so that they are presented as being 2x4 and 3x2, they do not qualify to be multiplied. Continuing with this first condition being satisfied, the next step would be determining the size of the matrix that results from the 2 matrices mentioned above being multiplied. In this case, the size of the resulting matrix would be 3x4, the row size steming from the initial matrix's row and the column size steming from the latter matrix's column size. After this has been determined, the multiplication procedure goes as follows. The 1st row of elements from the initial matrix would be each multiplied with each of the elements from the 1st column of the latter matrix. Each product resulting from each multiplication would then be added all together, and the result would be the element in the resulting matrix with the position Row1 and Column1 due to how it was conceived. The following procedure would then be applied to the 1st row of elements from the initial matrix to the 2nd column of the latter matrix. The result of that entire operation would be the 2nd element in the resulting matrix with the positions Row1 and Column2. This then would be applied until all rows and columns have succesfully been used for this operation.

The following code that adds and multiplies two 5x5 matrices:

In [97]:
Matrix1 = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
Matrix2 = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])

result = Matrix1 + Matrix2
print("Added")
print(result)

result = np.dot( Matrix1, Matrix2)
print("Multiplied")
print(result)

Added
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]
 [ 2  4  6  8 10]]
Multiplied
[[15 30 45 60 75]
 [15 30 45 60 75]
 [15 30 45 60 75]
 [15 30 45 60 75]
 [15 30 45 60 75]]


Question 3: Explain the concept of matrix transposition. What effect does it have on a 3×2 matrix? Write code to create a 3×2 matrix and find its transpose.

Matrix transposition is a process where we switch the matrix’s rows with its columns. For a 3×2
3×2 matrix, the transposition changes it from having 3 rows and 2 columns to having 2 rows and 3 columns. Essentially, the first row becomes the first column, the second row becomes the second column, and so on.

In [105]:
# Creating a 3x2 matrix
matrix_3x2 = np.array([[1, 2], [3, 4], [5, 6]])

# Finding the transpose
transpose_matrix = matrix_3x2.T
print("Original Matrix:\n", matrix_3x2)
print("Transpose:\n", transpose_matrix)

Original Matrix:
 [[1 2]
 [3 4]
 [5 6]]
Transpose:
 [[1 3 5]
 [2 4 6]]


Question 4: Create a random 5×5 matrix using NumPy. Compute the sum of all elements in the matrix, then find its transpose. Print both the sum and the transpose of the matrix.

In [108]:
# Create a random 5x5 matrix
random_matrix_5x5 = np.random.rand(5, 5)

# Calculate the sum of all elements in the matrix
sum_of_elements = np.sum(random_matrix_5x5)

# Find the transpose of the matrix
transpose_matrix = random_matrix_5x5.T

# Print results
print("Random 5x5 Matrix:\n", random_matrix_5x5)
print("Sum of all elements:", sum_of_elements)
print("Transpose of the matrix:\n", transpose_matrix)

Random 5x5 Matrix:
 [[0.83564419 0.07006352 0.49725715 0.80113883 0.43185541]
 [0.54717847 0.09313115 0.30925797 0.8687592  0.17176599]
 [0.29014661 0.64623773 0.59504671 0.86977431 0.54177737]
 [0.33474176 0.10252237 0.45418518 0.94433766 0.37212758]
 [0.86683209 0.76765746 0.30587923 0.92536667 0.4140841 ]]
Sum of all elements: 13.056768706221163
Transpose of the matrix:
 [[0.83564419 0.54717847 0.29014661 0.33474176 0.86683209]
 [0.07006352 0.09313115 0.64623773 0.10252237 0.76765746]
 [0.49725715 0.30925797 0.59504671 0.45418518 0.30587923]
 [0.80113883 0.8687592  0.86977431 0.94433766 0.92536667]
 [0.43185541 0.17176599 0.54177737 0.37212758 0.4140841 ]]


Question 5: Suppose you have two random 10×10 matrices D and E. Write code to (a) add the matrices, (b) subtract E from D, and (c) multiply D and E using matrix multiplication. Print each result and describe one possible application of each operation in computer science.

In [113]:
# Create a random 5x5 matrix D
D = np.random.rand(10, 10)
E = np.random.rand(10, 10)

print("Addition")
print("Matrix addition is used in computer graphics, especially in transformations like translation. For instance, adding translation vectors to the positions of objects in a 3D scene.")
print(D+E)
print("Substract E from D")
print("Matrix subtraction can be used in data analysis for finding the difference between two datasets. For example, comparing observed and expected values in machine learning to evaluate prediction errors.")
print(D-E)
print("Multiply D and E")
print("Matrix multiplication is fundamental in machine learning and neural networks for calculating the weighted sums during forward propagation. It’s also used in graph theory for operations like finding paths or connections between nodes.")
print(np.dot(D, E))

Addition
Matrix addition is used in computer graphics, especially in transformations like translation. For instance, adding translation vectors to the positions of objects in a 3D scene.
[[1.00424525 1.21211421 1.75513023 0.75177351 0.99567624 0.56208259
  1.53034177 1.18866964 0.73648106 0.34573018]
 [1.63299213 1.21516394 1.08722731 1.44933503 0.20505748 0.91631419
  1.12365411 0.87792108 1.6987728  1.07540303]
 [0.91192014 0.57874929 1.55760902 0.94766908 0.95388001 0.97311745
  1.39495499 1.10578517 0.3128979  0.47760642]
 [0.76028859 1.78917265 1.15849131 0.54270291 0.91079525 0.80064225
  0.74226333 0.69671438 0.55260184 0.71177227]
 [0.38181857 1.35220334 1.00932664 0.79365564 0.66045603 1.08082195
  1.02409816 0.37370223 0.71205009 0.74576465]
 [1.79022011 0.71040161 0.84174442 1.01512069 1.08838607 1.38656501
  1.38870647 0.79846105 0.7573778  1.07229115]
 [0.87261416 0.72252697 1.09422104 0.66260162 0.54478731 0.90785593
  0.85868129 1.4525042  1.0609255  1.04837   ]
 [1.5353