Q1: What are some examples of unary operatons in matrices?

Unary operations are operations that only involve and affect a single matrix. These are: Transpose (Flipping the matrix values over it's own diagonal, Trace (Sum of all diagonal values of the matrix), and Determinant (A value that represents certain properties of the matrix).

In [39]:
import numpy as np

# Create a 3x3 matrix
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Find the transpose
transpose_A = matrix_A.T

print("Matrix A:\n", matrix_A)
print("\nTranspose of Matrix A:\n", transpose_A)

# Check if the matrix is symmetric
is_symmetric = (matrix_A == matrix_A.T).all()
print("\nIs Matrix A symmetric? ", is_symmetric)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

Is Matrix A symmetric?  False


Q2: Check if matrix_A is a symmetric matrix. Modify the code below to verify this.

In [45]:
matrix_A = np.array([[1, 2, 3],
                     [2, 5, 6],
                     [3, 6, 9]])

# Find the transpose
transpose_A = matrix_A.T

print("Matrix A:\n", matrix_A)
print("\nTranspose of Matrix A:\n", transpose_A)

# Check if the matrix is symmetric
is_symmetric = (matrix_A == matrix_A.T).all()
print("\nIs Matrix A symmetric? ", is_symmetric)

Matrix A:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]

Transpose of Matrix A:
 [[1 2 3]
 [2 5 6]
 [3 6 9]]

Is Matrix A symmetric?  True


Practice Problem 1:
Create a 4  4×4 random matrix and check if it is symmetric.


In [59]:
# Your solution here
random_matrix = np.random.randint(1, 10, (4, 4))
transpose_random = random_matrix.T

# Check symmetry
is_symmetric_random = (random_matrix == transpose_random).all()
print("Random Matrix:\n", random_matrix)
print("\nIs the random matrix symmetric? ", is_symmetric_random)

Random Matrix:
 [[3 9 9 2]
 [8 8 4 8]
 [8 5 7 9]
 [1 1 4 7]]

Is the random matrix symmetric?  False


Q3: What is the trace of the following matrix?

In [62]:
matrix_B = np.array([[10, 20, 30],
                     [5, 15, 25],
                     [2, 4, 6]])

trace_B = np.trace(matrix_B)
print("\nTrace of Matrix B:", trace_B)


Trace of Matrix B: 31


Practice Problem 2:
Find the trace of a 5×5 identity matrix.


In [74]:
identity_matrix = np.eye(5)

trace_identity = np.trace(identity_matrix)
print(identity_matrix)
print("\nTrace of Identity Matrix:", trace_identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Trace of Identity Matrix: 5.0


Practice Problem 3:
Compute the determinant of the following 3×3 matrix using NumPy:


In [85]:
matrix_D = np.array([[1, 2, 3],
                     [0, 4, 5],
                     [1, 0, 6]])

det_D = np.linalg.det(matrix_D)
print(det_D)

22.000000000000004


Practice Problem 4: Application in Computer Science

Write code to generate a random 3×33 \times 33×3 matrix representing pixel intensities and find its transpose and determinant.

In [100]:
# Your solution here
random_matrix1 = np.random.randint(1, 10, (3, 3))
random_matrix2 = np.random.randint(1, 10, (3, 3))
print("\nrandom_matrix1:")
print(random_matrix1)
print("\nrandom_matrix2:")
print(random_matrix2)

random_product = np.dot(random_matrix1, random_matrix2)
print("\nrandom_product:")
print(random_product)
transpose_product = random_product.T
print("\ntranspose_product:")
print(transpose_product)
determinant_product = np.linalg.det(transpose_product) 
print("\ndeterminant_product:")
print(determinant_product)


random_matrix1:
[[9 6 7]
 [2 3 2]
 [4 8 2]]

random_matrix2:
[[1 9 6]
 [1 7 8]
 [7 8 3]]

random_product:
[[ 64 179 123]
 [ 19  55  42]
 [ 26 108  94]]

transpose_product:
[[ 64  19  26]
 [179  55 108]
 [123  42  94]]

determinant_product:
-7144.0000000000055


Practice Problem 5: Symmetric Matrices in Machine Learning

Symmetric matrices often appear in machine learning algorithms (e.g., covariance matrices). Create a symmetric 3×3 matrix and verify its properties.


In [103]:
A = np.array([[1, 2, 3],
              [2, 5, 6],
              [3, 6, 9]])

print("Matrix A:")
print(A)

# Verify if the matrix is symmetric
is_symmetric = np.array_equal(A, A.T)  # Check if A is equal to its transpose

print("\nTranspose of A:")
print(A.T)

print("\nIs the matrix symmetric? ", is_symmetric)

Matrix A:
[[1 2 3]
 [2 5 6]
 [3 6 9]]

Transpose of A:
[[1 2 3]
 [2 5 6]
 [3 6 9]]

Is the matrix symmetric?  True
