In [3]:
import numpy as np

Problem 1:

1. I check if the determinant of Matrix A is not 0
2. If that's true, I turn the Matrix A into an inverse.

In [7]:
A = np.array([[3,4],
              [2,5]])

det_A = np.linalg.det(A)

if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:")
    print(inv_A)
else:
    print("A is not invertible")

Inverse of A:
[[ 0.71428571 -0.57142857]
 [-0.28571429  0.42857143]]


Problem 2:

1. I check if the determinant of Matrix A is not 0
2. If that's true, I use a more efficient method of computing X like (np.linalg.solve(A, B))

In [29]:
A = np.array([[2,3],
              [4,-1]])

B = np.array([7,
              5])

if np.linalg.det(A) != 0:
    x = np.linalg.solve(A, B)
    print("Solution for [x,y]:")
    print(x)
else:
    print("A is not invertible, no unique solution")

Solution for [x,y]:
[1.57142857 1.28571429]


Problem 3:

1. I check if the determinant of Matrix A is not 0
2. If that's true, I turn the Matrix A into an inverse.

In [19]:
A = np.array([[1,2,3],
              [0,1,4],
              [5,6,0]])

det_A = np.linalg.det(A)

if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:")
    print(inv_A)
else:
    print("A is not invertible")

Inverse of A:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


Problem 4:

1. I check if the determinant of Matrix A is not 0
2. If that's true, I turn the Matrix A into an inverse.
3. I then directly multiply inversed Matrix A with Matrix B (not using a more efficient method) to solve for X

In [24]:
A = np.array([[1,1,1],
              [2,5,1],
              [2,3,8]])

B = np.array([6,
              -4,
              9])

inv_A = np.linalg.inv(A)
x = inv_A.dot(B)

print("Solution for [x,y]:")
print(x)

Solution for [x,y]:
[10.84210526 -5.21052632  0.36842105]


Problem 5:

1. I use a more efficient method (np.linalg.solve(A, B)) by directly computing them to solve for vector X

In [27]:
A = np.array([[4,-1,0],
              [3,5,2],
              [-2,4,1]])

B = np.array([5,
              6,
              2])

x = np.linalg.solve(A, B)

print("Solution for [x,y]:")
print(x)

Solution for [x,y]:
[  2.6   5.4 -14.4]


Bonus Challenge

In [34]:
def generate_random_square_matrices(size):
    # Generate two random square matrices of the given size
    matrix1 = np.random.randint(-10, 10, size=(size, size))  # Random integers between -10 and 10
    matrix2 = np.random.randint(-10, 10, size=(size, size))  # Random integers between -10 and 10
    
    return matrix1, matrix2

matrix1, matrix2 = generate_random_square_matrices(3)

product = np.dot(matrix1, matrix2)

if np.linalg.det(product) !=0:
    inverse = np.linalg.inv(product)
    print("Inverse:")
    print(inverse)
else:
    print("Not invertible")

Inverse:
[[-0.92222222  0.73333333  0.09305556]
 [-0.4         0.3         0.0125    ]
 [ 0.12777778 -0.11666667 -0.05694444]]
